name: Run Survey Data Pipeline

on:
  schedule:
    - cron: "0 */2 * * *"  # Cada 2 horas en punto (por ejemplo, 00:00, 02:00, 04:00, ...)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Configurar entorno R
      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"

      # 3. Instalar dependencias de sistema necesarias para algunos paquetes R
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libfontconfig1-dev \
            libfreetype6-dev

      # 4. Instalar paquetes R y ejecutar el script maestro
      - name: Install R dependencies and run the pipeline
        env:
          SERVIDOR: ${{ secrets.SERVIDOR }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          FORMID: ${{ secrets.FORMID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          Rscript -e "if (!require('pacman')) install.packages('pacman', repos = 'https://cloud.r-project.org')"
          Rscript -e "pacman::p_load(
            dplyr,
            tidyr,
            httr,
            jsonlite,
            googledrive,
            googlesheets4,
            writexl,
            haven,
            stringr,
            labelled,
            lubridate,
            gtsummary,
            dotenv
          )"
          Rscript BID_master_script.R

      # 5. Confirmación final
      - name: Confirm success
        run: echo "✅ Pipeline ejecutado correctamente."

